### ISSUE TITLE
READMEに使い方を追記する

### ISSUE THREAD

**Issue by otofune** [kyoppie/kyoppie-file#4]

**Comment by otofune** [comment]
requirements.txtも追加

**Comment by otofune** [comment]
Webでインストールしたモジュールに加え `pip install python-magic pillow` が必要らしいことがわかったけど他にあります？

**Comment by Petitsurume** [comment]
おいつのまにかありがとう

**Comment by otofune** [comment]
たぶん正しいと思う、わからんけど間違ってたら直してください
